package com.crushedlemon.chess.commons.model;

public enum GameResult {
    GAME_RESULT_UNKNOWN,
    GAME_RESULT_CHECKMATE,
    GAME_RESULT_RESIGNED,
    GAME_RESULT_DRAW_BY_OFFER,
    GAME_RESULT_DRAW_BY_STALEMATE,
    GAME_RESULT_DRAW_BY_REPETITION,
    GAME_RESULT_DRAW_BY_50_MOVE_RULE,
    GAME_RESULT_DRAW_BY_INSUFFICIENT_MATERIAL,
    GAME_RESULT_DRAW_BY_INSUFFICIENT_MATERIAL_VS_TIMEOUT,
    GAME_RESULT_TIMEOUT
}
