name: Publish Commons Library

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Debug
        run: |
          echo "Username = ${{ github.actor }}"
          echo "Token set? = ${{ secrets.GITHUB_TOKEN != '' }}"

      - name: Configure Maven for GitHub Packages
        run: |
          mkdir -p ~/.m2
          echo "<settings>
          <servers>
            <server>
              <id>github</id>
              <username>crushed-lemon</username>
              <password>${{ secrets.GH_PACKAGES_TOKEN }}</password>
            </server>
          </servers>
          </settings>" > ~/.m2/settings.xml

      - name: Build and Deploy
        run: mvn deploy
